### ISSUE TITLE
Version 3.1.0 installs on Python 2.7 but fails running

### ISSUE THREAD

**Issue by andy-maier** [pytest-dev/pytest-slack#227]
Two issues:

* pip installs pytest-messenger 3.1.0 on Python 2.7 even though that version does not run there (it fails in plugins.py line 13 on the type declarations that require Python 3.6 or higher and that were introduced in version 3.1.0 of the package). Pip does this because the package does not declare its supported Python versions using the `python_requires` argument of `setup()`.
  Solution: Add a `python_requires='>=3.6'` argument to `setup()` in `setup.py`.

* The Python versions stated in the "Programming Language" Trove classifiers still include Python 2.7 which is incorrect (Note that the Trove classifiers are not used by Pip to decide about Python version support).
  Solution: Remove Python 2.7 from the `classifiers` argument of `setup()` in `setup.py`.

**Comment by mrbean-bremen** [comment]
Also, in `setup.cfg` `universal` shall be set to 0 to avoid building Python2/3 wheels.
