### ISSUE TITLE
Add tests for different pytest versions.

### ISSUE THREAD

**Issue by LaserPhaser** [pytest-dev/pytest-slack#92]
We need to check pytest-slack with different pytest version. starting from 4.0

**Comment by a2lallenb** [comment]
Would it be possible to support slightly less current versions of pytest?
We have a problem with an Xray plugin and have locked into the following versions of pytest >  pytest>=3.5.1,<4.0.0

**Comment by LaserPhaser** [comment]
I see that  XRay plugin required pytest==4.3.1
Are you sure that you can't update you pytest up to 4 ? 
https://github.com/Isentia/pytest_xray/blob/master/requirements.txt

Anyway I'm going to try to support all major releases since 3.0

**Comment by LaserPhaser** [comment]
@a2lallenb  Unfortunately I can't support versions <4.3.0 fast.
So, for now, it's the minimal required version.
